routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group( [ 'middleware' => [ 'web' ] ], function(){

	Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');

	//Categories
	Route::resource( 'categories', 'CategoryController', [ 'except' => [ 'create' ] ] );

	//Tags
	Route::resource( 'tags', 'TagController', [ 'except' => [ 'create' ] ] );




	Route::get( 'blog/{slug}', [ 'as' => 'blog.single', 'uses' => 'BlogController@getSingle' ] )->where( 'slug', '[\w\d\-\_]+' );
	Route::get( 'blog', [ 'uses' => 'BlogController@getIndex', 'as' => 'blog.index' ] );
	Route::get( '/contact', 'PagesController@getContact' );
	Route::post( '/contact', 'PagesController@postContact' );

// Route::get('contact', 'ContactController@create')->name('contact.create');
// Route::post('contact', 'ContactController@store')->name('contact.store');

	Route::get( '/about', 'PagesController@about' );
	Route::get( '/', 'PagesController@index' );
	Route::resource( 'posts', 'PostController' );
});

Route::get( 'mail', 'mailController@index');
Route::post( 'postMail', 'mailController@post' );

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Auth::logout();

resources/views/partials/footer.blade.php
<p class="text-center">Copyright Affroapps 2017 &copy;</p>
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
@section( 'footer' )

resources/views/partials/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Laravel blog - @yield( 'title' ) </title>
<link href="/css/bootstrapx.min.css" rel="stylesheet">
{{ Html::style( 'css/bootstrap.min.css' ) }}

@yield( 'stylesheet' )

resources/views/partials/messages.blade.php
@if( Session::has( 'success' ) )

<div class="alert alert-success" role="alert">
	<strong>Success:</strong> {{ Session::get( 'success') }}
</div>

@endif

@if( count( $errors  ) > 0 )
<div class="alert alert-danger" role="alert">
	<strong>Errors:</strong> 
	@foreach( $errors->all() as $error )
		<p>{{ $error }}</p>
	@endforeach
</div>
@endif

resources/views/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Laravel Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{{ Request::is( '/' ) ? 'active' : '' }}"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li class="{{ Request::is( 'blog' ) ? 'active' : '' }}"><a href="/blog">Blog</a></li>
        <li class="{{ Request::is( 'about' ) ? 'active' : '' }}"><a href="/about">About</a></li>
        <li class="{{ Request::is( 'contact' ) ? 'active' : '' }}"><a href="/contact">Contact</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        @if (Auth::check())
        
        <li class="dropdown">
          <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {{ Auth::user()->name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ route('posts.index') }}">Posts</a></li>
            <li><a href="{{ route('categories.index') }}">Categories</a></li>
            <li><a href="{{ route('tags.index') }}">Tags</a></li>
            <li role="separator" class="divider"></li>
            <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
          </ul>
        </li>
        
        @else
        
          <a href="{{ route('login') }}" class="btn btn-default">Login</a>

        @endif

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>